### ISSUE TITLE
Alertmanager configuration

### ISSUE THREAD

**Issue by erhan-** [scottwallacesh/alertify#20]
Thank you for your effort with alertify! I am playing around with prometheus and would like to know how the route and receivers configuration has to look like to work with alertify.
Is the following way correct?

```
route:
    receiver: 'webhook_config'

receivers:
    - name: 'webhook_config'
    - url: http://alertify:8080 
```

**Comment by scottwallacesh** [comment]
It depends on how you want things configured.  As a concept what you have should work, but the YAML doesn't look quite right.

Try:
```yaml
route:
  receiver: webhook_config

receivers:
  - name: webhook_config
    webhook_configs:
      - url: http://alertify:8080/alert
```
